# Retrieval-Ready Study Assistant for NCERT Science

In [1]:
import fitz  # PyMuPDF

doc = fitz.open("iesc108.pdf")  
text = ""

for page in doc:
    text += page.get_text()

print(text[:2000])

Journey Inside
the Atom
Chapter
8
Everything that you see or observe, or feel around is
matter. You have learnt that matter consists of tiny
particles called atoms. Take a closer look at the picture
given above. What do you observe? Do you notice that both living
beings, like us, and non-living things, like a house, are ultimately
composed of atoms? These atoms are so tiny that they cannot be
seen with the naked eye.
You may be wondering — Is an atom truly the smallest unit of
matter, or can it be divided even further?
Scientists, too, have been exploring whether atoms are divisible.
If so, what are their constituents and how are these arranged?
Let us examine how the concept of atoms emerged and how it has
been evolved since then.
Grade 8
Curiosity
Chapter 7
Atoms
Si
N
O
H
P
C
Human Body
Organ
Tissue
Cell
Silicates
Brick
Wall
Room
House
Protein
Cell
Think It Over
	y
Are atoms the
smallest indivisible
particles?
	y
Why do electrons
not fall into the
nucleus even
though they
are attracted to
protons in it?
	y
Why did scientists
keep modifying
atomic models?
141
Journey Inside the Atom
8.1 Rediscovering the Roots of Atomic Theory
Let us embark on a journey that takes us back more than 2,000 years, to the
intellectual landscapes of ancient India and ancient Greece. In these distant
yet remarkably parallel civilisations, profound thinkers, such as Acharya
Kanada in India, and Leucippus and Democritus in Greece, pondered
over the same fundamental question that has continued to inspire human
inquiry across centuries — What is everything made up of?
Acharya Kanada suggested that if matter (dravya) is divided repeatedly,
you will reach a stage where you would encounter the smallest particles
that can no longer be divided. He called these particles parmanus. His ideas
are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely
small and cannot be perceived by the senses. Combinations of these forms
dyads (groups of two parmanus

In [2]:
import re

clean_lines = []

for line in text.split("\n"):
    line = line.strip()
    
    if not line:
        continue
    
    # Remove pure numbers (page numbers)
    if line.isdigit():
        continue
    
    # Remove very short lines (likely diagram labels)
    if len(line.split()) <= 2:
        continue
    
    # Remove lines that look like section garbage
    if re.match(r"Grade|Chapter \d|Curiosity", line):
        continue
    
    clean_lines.append(line)

clean_text = "\n".join(clean_lines)

print(clean_text[:1500])

Everything that you see or observe, or feel around is
matter. You have learnt that matter consists of tiny
particles called atoms. Take a closer look at the picture
given above. What do you observe? Do you notice that both living
beings, like us, and non-living things, like a house, are ultimately
composed of atoms? These atoms are so tiny that they cannot be
seen with the naked eye.
You may be wondering — Is an atom truly the smallest unit of
matter, or can it be divided even further?
Scientists, too, have been exploring whether atoms are divisible.
If so, what are their constituents and how are these arranged?
Let us examine how the concept of atoms emerged and how it has
been evolved since then.
Think It Over
Are atoms the
Why do electrons
not fall into the
are attracted to
protons in it?
Why did scientists
Journey Inside the Atom
8.1 Rediscovering the Roots of Atomic Theory
Let us embark on a journey that takes us back more than 2,000 years, to the
intellectual landscapes of ancient India and ancient Greece. In these distant
yet remarkably parallel civilisations, profound thinkers, such as Acharya
Kanada in India, and Leucippus and Democritus in Greece, pondered
over the same fundamental question that has continued to inspire human
inquiry across centuries — What is everything made up of?
Acharya Kanada suggested that if matter (dravya) is divided repeatedly,
you will reach a stage where you would encounter the smallest particles
that can no longer be divided. He called t

In [3]:
import re

clean_lines = []

skip_section = False

for line in text.split("\n"):
    line = line.strip()

    if not line:
        continue

    # Start skipping when Think It Over appears
    if "Think It Over" in line:
        skip_section = True
        continue

    # Stop skipping when next numbered section starts (like 8.1)
    if re.match(r"\d+\.\d+", line):
        skip_section = False

    if skip_section:
        continue

    # Remove page numbers
    if line.isdigit():
        continue

    # Remove very short lines
    if len(line.split()) <= 2:
        continue

    clean_lines.append(line)

clean_text = "\n".join(clean_lines)

print(clean_text[:1500])

Everything that you see or observe, or feel around is
matter. You have learnt that matter consists of tiny
particles called atoms. Take a closer look at the picture
given above. What do you observe? Do you notice that both living
beings, like us, and non-living things, like a house, are ultimately
composed of atoms? These atoms are so tiny that they cannot be
seen with the naked eye.
You may be wondering — Is an atom truly the smallest unit of
matter, or can it be divided even further?
Scientists, too, have been exploring whether atoms are divisible.
If so, what are their constituents and how are these arranged?
Let us examine how the concept of atoms emerged and how it has
been evolved since then.
8.1 Rediscovering the Roots of Atomic Theory
Let us embark on a journey that takes us back more than 2,000 years, to the
intellectual landscapes of ancient India and ancient Greece. In these distant
yet remarkably parallel civilisations, profound thinkers, such as Acharya
Kanada in India, and Leucippus and Democritus in Greece, pondered
over the same fundamental question that has continued to inspire human
inquiry across centuries — What is everything made up of?
Acharya Kanada suggested that if matter (dravya) is divided repeatedly,
you will reach a stage where you would encounter the smallest particles
that can no longer be divided. He called these particles parmanus. His ideas
are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely
small and cannot be perceiv

In [4]:
paragraphs = clean_text.split("\n")

chunks = []
current_chunk = ""

for para in paragraphs:
    para = para.strip()
    
    if not para:
        continue
    
    if len(current_chunk) + len(para) < 800:
        current_chunk += " " + para
    else:
        chunks.append(current_chunk.strip())
        current_chunk = para

if current_chunk:
    chunks.append(current_chunk.strip())

print("Total chunks:", len(chunks))
print("\nFirst chunk:\n")
print(chunks[0])

Total chunks: 56

First chunk:

Everything that you see or observe, or feel around is matter. You have learnt that matter consists of tiny particles called atoms. Take a closer look at the picture given above. What do you observe? Do you notice that both living beings, like us, and non-living things, like a house, are ultimately composed of atoms? These atoms are so tiny that they cannot be seen with the naked eye. You may be wondering — Is an atom truly the smallest unit of matter, or can it be divided even further? Scientists, too, have been exploring whether atoms are divisible. If so, what are their constituents and how are these arranged? Let us examine how the concept of atoms emerged and how it has been evolved since then. 8.1 Rediscovering the Roots of Atomic Theory

In [5]:
import re
from rank_bm25 import BM25Okapi

def tokenize(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", "", text)  # remove punctuation
    return text.split()

tokenized_chunks = [tokenize(chunk) for chunk in chunks]
bm25 = BM25Okapi(tokenized_chunks)

print("Improved BM25 index created!")

Improved BM25 index created!

In [6]:
query = "parmanus"

tokenized_query = query.split()

results = bm25.get_top_n(tokenized_query, chunks, n=3)

for i, r in enumerate(results):
    print(f"\nResult {i+1}:\n")
    print(r)

Result 1:

dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all

Result 2:

Let us embark on a journey that takes us back more than 2,000 years, to the intellectual landscapes of ancient India and ancient Greece. In these distant yet remarkably parallel civilisations, profound thinkers, such as Acharya Kanada in India, and Leucippus and Democritus in Greece, pondered over the same fundamental question that has continued to inspire human inquiry across centuries — What is everything made up of? Acharya Kanada suggested that if matter (dravya) is divided repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms

Result 3:

 What part of the film or documentary did you find most interesting, and what question do you still have? y Draw a bar graph showing the number of electrons in each energy level for any three elements. y To learn more about atoms, you can explore the links given below: The Quest Continues ... Is it possible to completely understand everything that happens inside an The Journey Beyond

In [7]:
from google import genai

client = genai.Client(api_key="AIzaSyAyOLH2F19ZqVOdFInF_daQWM15MCrAx8k")

def answer(question):
    tokenized_query = question.split()
    retrieved = bm25.get_top_n(tokenized_query, chunks, n=3)
    context = "\n\n".join(retrieved)

    prompt = f"""
You are a Grade 8 Science assistant.

Answer ONLY using the context below.
If the answer is not clearly supported by the context, say:
"I cannot answer from the provided chapter."

Context:
{context}

Question:
{question}
"""

    response = client.models.generate_content(
        model="gemini-1.5-flash-latest",
        contents=prompt,
        config={"temperature": 0}
    )

    return response.text, retrieved

In [8]:
from google import genai

client = genai.Client(api_key="AIzaSyAyOLH2F19ZqVOdFInF_daQWM15MCrAx8k")

models = client.models.list()

for m in models:
    print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-3.1-flash-tts-preview
models/gemini-robotics-er-1.5-preview
models/gemini-robotics-er-1.6-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/gemini-embedding-2
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/veo-3.1-lite-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025
models/gemini-3.1-flash-live-preview

In [9]:
from google import genai

client = genai.Client(api_key="AIzaSyAyOLH2F19ZqVOdFInF_daQWM15MCrAx8k")

def answer(question):
    tokenized_query = question.split()
    retrieved = bm25.get_top_n(tokenized_query, chunks, n=3)
    context = "\n\n".join(retrieved)

    prompt = f"""
You are a Grade 8 Science assistant.

Answer ONLY using the context below.
If the answer is not clearly supported by the context, say:
"I cannot answer from the provided chapter."

Context:
{context}

Question:
{question}
"""

    response = client.models.generate_content(
        model="models/gemini-2.5-flash",
        contents=prompt,
        config={"temperature": 0}
    )

    return response.text, retrieved

In [10]:
ans, retrieved = answer("What is parmanus?")
print(ans)

I cannot answer from the provided chapter.

In [11]:
ans, retrieved = answer("What is parmanus?")

print("MODEL ANSWER:\n")
print(ans)

print("\n\nRETRIEVED CHUNKS:\n")
for i, r in enumerate(retrieved):
    print(f"\n--- Chunk {i+1} ---\n")
    print(r)

MODEL ANSWER:

I cannot answer from the provided chapter.


RETRIEVED CHUNKS:


--- Chunk 1 ---

(i)	 Both A and R are true, and R is the correct explanation of A. (ii)	 Both A and R are true, but R is not the correct explanation of A. (iii)	 A is true, but R is false. (iv)	 A is false, but R is true. 8.	 Magnesium is essential for many biological processes, including muscle contraction. For an atom of magnesium with a mass number of 24 and atomic number 12, determine the number of (i) protons, (ii) neutrons, (iii) electrons, and also illustrate the arrangement of electrons in a magnesium atom. 9.	 Find the following information for the elements shown in Fig. 8.17: (i)	 Name of the element (iii)	 Total number of electrons (iv)	 Number of valence electrons (v)	 Valency of the element (vi)	 Number of protons (vii)	 Atomic number

--- Chunk 2 ---

Rutherford found that the nucleus is extremely small — about 105 (one lakh) times smaller than the atom. He calculated that the diameter of an atom is ≈ 10−10 m, and the diameter of the nucleus is ≈ 10–15 m. You can imagine that if an atom were of the size of a cricket ground (about 100 m across), the nucleus would be just a tiny black pepper grain (a few mm) at Can you calculate how many atoms would be needed to make a sheet of paper that is 0.1 mm thick, like the one in your textbook? If the diameter of one atom is about 10–10 m, and the sheet is 0.1 mm (10–4 m) thick, number of atoms ≈ (10–4 m) ÷ (10–10 m) = 106. That is about one million atoms need to be stacked together! When these atoms come together, they form the solid materials we see and touch. What feels

--- Chunk 3 ---

two electrons in case of helium), the atom is stable and largely y Valency is the combining capacity of an atom. It is equal to the number of electrons which can be gained, lost or shared by an atom to achieve a stable configuration. y The atomic number of an element is equal to the number of protons in its nucleus. y The mass number of an atom is equal to the total number of nucleons (protons and neutrons) in its nucleus. y Isotopes are atoms of same element that have the same atomic number but different mass numbers. y The average atomic mass of an element is calculated based on the relative abundance of its isotopes in nature. y Isobars are atoms of different elements with the same mass number but different atomic numbers. At a Glance

In [12]:
for i, chunk in enumerate(chunks):
    if "parmanu" in chunk.lower():
        print("Found in chunk:", i)
        print(chunk)
        print("\n" + "="*50 + "\n")

Found in chunk: 1
Let us embark on a journey that takes us back more than 2,000 years, to the intellectual landscapes of ancient India and ancient Greece. In these distant yet remarkably parallel civilisations, profound thinkers, such as Acharya Kanada in India, and Leucippus and Democritus in Greece, pondered over the same fundamental question that has continued to inspire human inquiry across centuries — What is everything made up of? Acharya Kanada suggested that if matter (dravya) is divided repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms

==================================================

Found in chunk: 2
dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all

==================================================

In [13]:
import re

stopwords = {
    "what", "is", "who", "the", "of", "a", "an",
    "in", "to", "and", "are", "was", "were"
}

def tokenize(text):
    words = re.findall(r"\w+", text.lower())
    return [w for w in words if w not in stopwords]

In [14]:
tokenized_chunks = [tokenize(chunk) for chunk in chunks]
bm25 = BM25Okapi(tokenized_chunks)

In [15]:
ans, retrieved = answer("What is parmanus?")
print(ans)

for r in retrieved:
    print("\n---\n", r)

I cannot answer from the provided chapter.

---
  What part of the film or documentary did you find most interesting, and what question do you still have? y Draw a bar graph showing the number of electrons in each energy level for any three elements. y To learn more about atoms, you can explore the links given below: The Quest Continues ... Is it possible to completely understand everything that happens inside an The Journey Beyond

---
 everyday life across fields, such as healthcare, energy, agriculture y Create a role-play stage play or story about the ‘Journey Inside the Atom’, and the scientists who discovered and contributed to the identification of atomic structure. y Use selected software or digital tools and try to create animations or simulations of various atomic models, and share them in the class. y Watch a film or documentary about the structure of the atom and write a report answering the following questions:  Which film or documentary did you watch, and what was its main idea or topic?  What did the film or documentary teach you about the structure of the atom and the atomic model(s)?  Which scientists were mentioned in the film or documentary, and what were their contributions?

---
 (v)	How many valence electrons does it have? (vi)	What will be the mass number if two neutrons are added to its (vii)	What will be the relation of X with the new atom? 15.	 In an atom, there are 12 protons and 12 neutrons in the nucleus. Now, imagine that all the electrons are replaced with some hypothetical particles that have the same charge as electrons but are 500 times heavier. What effect will this replacement have on the atom’s: (i)	Atomic number (ii)	Atomic mass (iii)	Mass number (iv)	Overall charge Journey Inside the Atom y Create an ‘Atomic Prediction Board’ game based on atomic number, mass number, number of electrons, protons, neutrons and valency. Students may predict elements using atomic clues. y Prepare a report on how the properties of atoms impact us in

In [16]:
import re

def remove_activity_sections(text):
    patterns = [
        r"Think It Over.*?(?=\n\n)",
        r"Pause and Ponder.*?(?=\n\n)",
        r"The Quest Continues.*?(?=\n\n)",
        r"At a Glance.*?(?=\n\n)",
        r"\d+\.\s+.*?(?=\n\n)",  # numbered questions
        r"Create .*?(?=\n\n)",
        r"Draw .*?(?=\n\n)",
        r"Prepare .*?(?=\n\n)",
        r"Watch .*?(?=\n\n)"
    ]
    
    for pattern in patterns:
        text = re.sub(pattern, "", text, flags=re.DOTALL)
    
    return text

In [17]:
clean_text = remove_activity_sections(clean_text)

In [18]:
def chunk_text(text, chunk_size=250, overlap=40):
    words = text.split()
    chunks = []

    for i in range(0, len(words), chunk_size - overlap):
        chunk = " ".join(words[i:i+chunk_size])
        chunks.append(chunk)

    return chunks

chunks = chunk_text(clean_text, chunk_size=250, overlap=40)

print("Total chunks:", len(chunks))

Total chunks: 36

In [19]:
stopwords = {
    "what", "is", "who", "the", "of", "a", "an",
    "in", "to", "and", "are", "was", "were"
}

def tokenize(text):
    words = re.findall(r"\w+", text.lower())
    return [w for w in words if w not in stopwords]

In [20]:
from rank_bm25 import BM25Okapi

tokenized_chunks = [tokenize(chunk) for chunk in chunks]

bm25 = BM25Okapi(tokenized_chunks)

print("BM25 rebuilt successfully.")

BM25 rebuilt successfully.

In [28]:
query = "What is parmanus?"
tokenized_query = tokenize(query)

results = bm25.get_top_n(tokenized_query, chunks, n=1)

for i, r in enumerate(results):
    print(f"\n--- Result {i+1} ---\n")
    print(r)

--- Result 1 ---

repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all matter is composed of indivisible particles called atoms. That is, the atoms are the fundamental building blocks of matter that cannot be broken down into smaller parts. Dalton’s atomic theory was the first scientific description of how matter is made. It became the starting point for the current understanding of atomic structure. You may be wondering how Dalton’s idea evolved into a model for the structure of the atom. Following Dalton’s theory, scientists were curious to know the answers of the questions: y What are

In [31]:
import ollama

def answer(question):

    # Step 1: Retrieve
    tokenized_query = tokenize(question)
    retrieved = bm25.get_top_n(tokenized_query, chunks, n=1)

    # Step 2: Build context
    context = "\n\n".join(retrieved)

    # 🔎 DEBUG PRINT HERE
    print("=== RETRIEVED CONTEXT ===")
    print(context)
    print("=========================")

    # Step 3: Prompt
    prompt = f"""
You are a Grade 8 Science assistant.

Use ONLY the information from the context below.

If the answer is clearly present, explain it in simple words.
If not present, say:
"I cannot answer from the provided chapter."

Context:
{context}

Question:
{question}

Answer clearly in 4–6 simple sentences.
"""

    # Step 4: Call Ollama
    response = ollama.chat(
        model="gemma:7b",
        messages=[{"role": "user", "content": prompt}]
    )

    return response["message"]["content"], retrieved

In [32]:
ans, retrieved = answer("What is parmanus?")
print("\n=== FINAL ANSWER ===")
print(ans)

=== RETRIEVED CONTEXT ===
repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all matter is composed of indivisible particles called atoms. That is, the atoms are the fundamental building blocks of matter that cannot be broken down into smaller parts. Dalton’s atomic theory was the first scientific description of how matter is made. It became the starting point for the current understanding of atomic structure. You may be wondering how Dalton’s idea evolved into a model for the structure of the atom. Following Dalton’s theory, scientists were curious to know the answers of the questions: y What are
=========================

=== FINAL ANSWER ===
Parmanus are the smallest particles that cannot be divided further. They are infinitely small and cannot be perceived by the senses.

# Evaluation

In [33]:
test_questions = [
    "What is parmanus?",
    "Who was Acharya Kanada?",
    "What did Dalton propose about atoms?",
    "What does atomos mean?",
    "What is an atom?"
]

In [34]:
for q in test_questions:
    ans, retrieved = answer(q)
    print("\nQUESTION:", q)
    print("ANSWER:", ans)
    print("-" * 80)

=== RETRIEVED CONTEXT ===
repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all matter is composed of indivisible particles called atoms. That is, the atoms are the fundamental building blocks of matter that cannot be broken down into smaller parts. Dalton’s atomic theory was the first scientific description of how matter is made. It became the starting point for the current understanding of atomic structure. You may be wondering how Dalton’s idea evolved into a model for the structure of the atom. Following Dalton’s theory, scientists were curious to know the answers of the questions: y What are
=========================

QUESTION: What is parmanus?
ANSWER: Parmanus are the smallest particles that cannot be divided further. They are infinitely small and cannot be perceived by the senses. These particles combine in different ways to form all the material in the universe, including living beings.
--------------------------------------------------------------------------------
=== RETRIEVED CONTEXT ===
Everything that you see or observe, or feel around is matter. You have learnt that matter consists of tiny particles called atoms. Take a closer look at the picture given above. What do you observe? Do you notice that both living beings, like us, and non-living things, like a house, are ultimately composed of atoms? These atoms are so tiny that they cannot be seen with the naked eye. You may be wondering — Is an atom truly the smallest unit of matter, or can it be divided even further? Scientists, too, have been exploring whether atoms are divisible. If so, what are their constituents and how are these arranged? Let us examine how the concept of atoms emerged and how it has been evolved since then. 8.1 Rediscovering the Roots of Atomic Theory Let us embark on a journey that takes us back more than 2,000 years, to the intellectual landscapes of ancient India and ancient Greece. In these distant yet remarkably parallel civilisations, profound thinkers, such as Acharya Kanada in India, and Leucippus and Democritus in Greece, pondered over the same fundamental question that has continued to inspire human inquiry across centuries — What is everything made up of? Acharya Kanada suggested that if matter (dravya) is divided repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and
=========================

QUESTION: Who was Acharya Kanada?
ANSWER: The provided text does not contain any information regarding who Acharya Kanada was, so I am unable to answer this question from the given chapter.
--------------------------------------------------------------------------------
=== RETRIEVED CONTEXT ===
each statement. (i) Electrons lose energy while moving in fixed orbits and slowly fall into the nucleus. (ii) Electrons can exist anywhere around the nucleus with no fixed (iii) Electrons revolve around the nucleus in orbits of fixed energy without losing energy. (iv) Electrons can be found between energy levels as they move around the nucleus. 3. The composition of the nuclei of three atomic species X, Y, and Z are given as follows. Number of protons Number of neutrons Explain the relation between the following: (i) Y and Z (ii) Z and X 4. What conclusion did Rutherford draw about the position and characteristics of the atom’s positively charged part based on the few alpha particles that bounced back or were deflected at large angles in the gold foil experiment? Revise, Reflect, Refine Journey Inside the Atom 5. Explain and arrange the following statements in the correct chronological order to show how atomic models have evolved over (i) Bohr’s model proposed that electrons move in fixed orbits around the nucleus, each with a definite energy. (ii) Thomson’s model depicted the atom as a ʻplum puddingʼ with electrons embedded in a sphere of positive charge. (iii) Rutherford’s model proposed that atoms have a dense central (iv) Dalton’s model described atoms as indivisible particles. 6. Electrons move around the nucleus in orbits. Why do they not fly away from the atom? Explain what keeps them attracted to the nucleus. 7. Assertion (A): The discovery of subatomic particles helped in understanding the
=========================

QUESTION: What did Dalton propose about atoms?
ANSWER: The provided text does not contain any information regarding Dalton's proposals about atoms, so I am unable to answer this question from the given context.
--------------------------------------------------------------------------------
=== RETRIEVED CONTEXT ===
in two isotopic forms. One isotope has a mass of 35 u, and the other has a mass of 37 u. They occur in the ratio 3:1. This raises an interesting question — should we consider the mass of a chlorine atom to be 35 u or 37 u? If the atomic mass of a natural element is taken as the average mass of all its naturally occurring isotopes, it would be the simple arithmetic mean of the masses of its isotopes, calculated without accounting for the relative abundances of each isotope. For chlorine, with isotopes ³⁵ Cl and ³⁷ Cl, the simple average would be — Average atomic mass = = 36 u However, this does not accurately reflect nature, since isotopes do not occur in equal ratios. The more common isotope is ³⁵ Cl, which constitutes about 75% while the other isotope, ³⁷ Cl makes up about 25%. The accurate average atomic mass can be calculated by considering their natural abundances. This is called a weighted average atomic mass, which can be calculated by multiplying the mass of each isotope by its percent relative abundance and then adding the two values, as explained below. This does not mean that any one atom of chlorine has a fractional mass of 35.5 u. It means that if you take, say 1 million chlorine atoms, they will contain 7.5 lakh 35 and 2.5 lakh 37 17 Cl atoms with a weighted average atomic mass of 35.5 u. This comparison shows that
=========================

QUESTION: What does atomos mean?
ANSWER: The provided text does not contain any information regarding the meaning of "atomos," so I am unable to answer this question from the given context.
--------------------------------------------------------------------------------
=== RETRIEVED CONTEXT ===
of atomic energy in India. He established key institutions like the Tata Institute of Fundamental Research (TIFR) and the Bhabha Atomic Research Centre (BARC), for peaceful uses of atomic energy to generate electricity, support agriculture, and advanced medical treatments. Journey Inside the Atom Fig. 8.16: Journey of the development of atomic models y Atoms are the building blocks of matter. y J. J. Thomson proposed that in an atom, electrons are embedded in a positively charged sphere. y Rutherford’s model described the atom as mostly empty space, with a dense, positively charged nucleus at its centre and electrons y Niels Bohr’s model proposed that electrons move in fixed energy levels (shells) around the nucleus. y The shells of an atom are named as K, L, M, N, and so on. y James Chadwick discovered the presence of neutrons in the atom. y The three subatomic particles of an atom are electrons, protons, y If the outermost shell of an atom has an octet of electrons (or two electrons in case of helium), the atom is stable and largely y Valency is the combining capacity of an atom. It is equal to the number of electrons which can be gained, lost or shared by an atom to achieve a stable configuration. y The atomic number of an element is equal to the number of protons in its nucleus. y The mass number of an atom is equal to the total number of nucleons (protons and neutrons) in its nucleus. y Isotopes
=========================

QUESTION: What is an atom?
ANSWER: An atom is the basic building block of matter, consisting of electrons embedded in a positively charged sphere. It contains a dense, positively charged nucleus at its centre, with electrons moving in fixed energy levels (shells) around it.
--------------------------------------------------------------------------------

| Question                 | Correct | Grounded | Refusal Appropriate |
| ------------------------ | ------- | -------- | ------------------- |
| What is parmanus?        | Yes     | Yes      | N/A                 |
| Who was Acharya Kanada?  | No      | Yes      | Yes                 |
| What did Dalton propose? | No      | Yes      | Yes                 |
| What does atomos mean?   | No      | Yes      | Yes                 |
| What is an atom?         | Yes     | Yes      | N/A                 |

In [36]:
import pandas as pd

questions = [
    "What is parmanus?",
    "Who was Acharya Kanada?",
    "What did Dalton propose about atoms?",
    "What does atomos mean?",
    "What is an atom?"
]

results_data = []

for q in questions:
    ans, retrieved = answer(q)
    
    results_data.append({
        "question": q,
        "answer": ans,
        "retrieved_chunk": retrieved[0] if retrieved else ""
    })

# Create dataframe
df = pd.DataFrame(results_data)

# Show it
df

=== RETRIEVED CONTEXT ===
repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all matter is composed of indivisible particles called atoms. That is, the atoms are the fundamental building blocks of matter that cannot be broken down into smaller parts. Dalton’s atomic theory was the first scientific description of how matter is made. It became the starting point for the current understanding of atomic structure. You may be wondering how Dalton’s idea evolved into a model for the structure of the atom. Following Dalton’s theory, scientists were curious to know the answers of the questions: y What are
=========================
=== RETRIEVED CONTEXT ===
Everything that you see or observe, or feel around is matter. You have learnt that matter consists of tiny particles called atoms. Take a closer look at the picture given above. What do you observe? Do you notice that both living beings, like us, and non-living things, like a house, are ultimately composed of atoms? These atoms are so tiny that they cannot be seen with the naked eye. You may be wondering — Is an atom truly the smallest unit of matter, or can it be divided even further? Scientists, too, have been exploring whether atoms are divisible. If so, what are their constituents and how are these arranged? Let us examine how the concept of atoms emerged and how it has been evolved since then. 8.1 Rediscovering the Roots of Atomic Theory Let us embark on a journey that takes us back more than 2,000 years, to the intellectual landscapes of ancient India and ancient Greece. In these distant yet remarkably parallel civilisations, profound thinkers, such as Acharya Kanada in India, and Leucippus and Democritus in Greece, pondered over the same fundamental question that has continued to inspire human inquiry across centuries — What is everything made up of? Acharya Kanada suggested that if matter (dravya) is divided repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and
=========================
=== RETRIEVED CONTEXT ===
each statement. (i) Electrons lose energy while moving in fixed orbits and slowly fall into the nucleus. (ii) Electrons can exist anywhere around the nucleus with no fixed (iii) Electrons revolve around the nucleus in orbits of fixed energy without losing energy. (iv) Electrons can be found between energy levels as they move around the nucleus. 3. The composition of the nuclei of three atomic species X, Y, and Z are given as follows. Number of protons Number of neutrons Explain the relation between the following: (i) Y and Z (ii) Z and X 4. What conclusion did Rutherford draw about the position and characteristics of the atom’s positively charged part based on the few alpha particles that bounced back or were deflected at large angles in the gold foil experiment? Revise, Reflect, Refine Journey Inside the Atom 5. Explain and arrange the following statements in the correct chronological order to show how atomic models have evolved over (i) Bohr’s model proposed that electrons move in fixed orbits around the nucleus, each with a definite energy. (ii) Thomson’s model depicted the atom as a ʻplum puddingʼ with electrons embedded in a sphere of positive charge. (iii) Rutherford’s model proposed that atoms have a dense central (iv) Dalton’s model described atoms as indivisible particles. 6. Electrons move around the nucleus in orbits. Why do they not fly away from the atom? Explain what keeps them attracted to the nucleus. 7. Assertion (A): The discovery of subatomic particles helped in understanding the
=========================
=== RETRIEVED CONTEXT ===
in two isotopic forms. One isotope has a mass of 35 u, and the other has a mass of 37 u. They occur in the ratio 3:1. This raises an interesting question — should we consider the mass of a chlorine atom to be 35 u or 37 u? If the atomic mass of a natural element is taken as the average mass of all its naturally occurring isotopes, it would be the simple arithmetic mean of the masses of its isotopes, calculated without accounting for the relative abundances of each isotope. For chlorine, with isotopes ³⁵ Cl and ³⁷ Cl, the simple average would be — Average atomic mass = = 36 u However, this does not accurately reflect nature, since isotopes do not occur in equal ratios. The more common isotope is ³⁵ Cl, which constitutes about 75% while the other isotope, ³⁷ Cl makes up about 25%. The accurate average atomic mass can be calculated by considering their natural abundances. This is called a weighted average atomic mass, which can be calculated by multiplying the mass of each isotope by its percent relative abundance and then adding the two values, as explained below. This does not mean that any one atom of chlorine has a fractional mass of 35.5 u. It means that if you take, say 1 million chlorine atoms, they will contain 7.5 lakh 35 and 2.5 lakh 37 17 Cl atoms with a weighted average atomic mass of 35.5 u. This comparison shows that
=========================
=== RETRIEVED CONTEXT ===
of atomic energy in India. He established key institutions like the Tata Institute of Fundamental Research (TIFR) and the Bhabha Atomic Research Centre (BARC), for peaceful uses of atomic energy to generate electricity, support agriculture, and advanced medical treatments. Journey Inside the Atom Fig. 8.16: Journey of the development of atomic models y Atoms are the building blocks of matter. y J. J. Thomson proposed that in an atom, electrons are embedded in a positively charged sphere. y Rutherford’s model described the atom as mostly empty space, with a dense, positively charged nucleus at its centre and electrons y Niels Bohr’s model proposed that electrons move in fixed energy levels (shells) around the nucleus. y The shells of an atom are named as K, L, M, N, and so on. y James Chadwick discovered the presence of neutrons in the atom. y The three subatomic particles of an atom are electrons, protons, y If the outermost shell of an atom has an octet of electrons (or two electrons in case of helium), the atom is stable and largely y Valency is the combining capacity of an atom. It is equal to the number of electrons which can be gained, lost or shared by an atom to achieve a stable configuration. y The atomic number of an element is equal to the number of protons in its nucleus. y The mass number of an atom is equal to the total number of nucleons (protons and neutrons) in its nucleus. y Isotopes
=========================

,question,answer,retrieved_chunk
0,What is parmanus?,Parmanus are the smallest particles that canno...,"repeatedly, you will reach a stage where you w..."
1,Who was Acharya Kanada?,The provided text does not contain any informa...,"Everything that you see or observe, or feel ar..."
2,What did Dalton propose about atoms?,The provided text does not contain any informa...,each statement. (i) Electrons lose energy whil...
3,What does atomos mean?,The provided text does not contain any informa...,in two isotopic forms. One isotope has a mass ...
4,What is an atom?,"An atom is the basic building block of matter,...",of atomic energy in India. He established key ...

In [37]:
df["correct"] = [
    "yes",   # What is parmanus?
    "no",    # Who was Acharya Kanada?
    "no",    # What did Dalton propose about atoms?
    "no",    # What does atomos mean?
    "yes"    # What is an atom?
]

df["grounded"] = [
    "yes",
    "yes",
    "yes",
    "yes",
    "yes"
]

df["refusal_appropriate"] = [
    "N/A",
    "no",
    "yes",
    "yes",
    "N/A"
]

df

,question,answer,retrieved_chunk,correct,grounded,refusal_appropriate
0,What is parmanus?,Parmanus are the smallest particles that canno...,"repeatedly, you will reach a stage where you w...",yes,yes,N/A
1,Who was Acharya Kanada?,The provided text does not contain any informa...,"Everything that you see or observe, or feel ar...",no,yes,no
2,What did Dalton propose about atoms?,The provided text does not contain any informa...,each statement. (i) Electrons lose energy whil...,no,yes,yes
3,What does atomos mean?,The provided text does not contain any informa...,in two isotopic forms. One isotope has a mass ...,no,yes,yes
4,What is an atom?,"An atom is the basic building block of matter,...",of atomic energy in India. He established key ...,yes,yes,N/A

In [38]:
df.to_csv("evaluation_results.csv", index=False)

Q: What improvements would you make to the system?

Answer:

The current system performs well for direct, definition-based questions but shows limitations in retrieval and interpretation. Several improvements can enhance its performance.

First, the chunking strategy can be improved. Currently, large chunks sometimes mix multiple concepts, which makes it harder for BM25 to retrieve the most relevant information. Using smaller, sentence-level or paragraph-level chunks would improve retrieval precision.

Second, the retrieval mechanism can be enhanced. BM25 relies only on keyword matching, which causes failures when questions are phrased differently. This can be improved by using hybrid retrieval (BM25 + embeddings) so that semantic similarity is also considered.

Third, the prompt design can be refined. The model sometimes refuses to answer even when relevant information is present but not explicitly defined. Adding better instructions or examples in the prompt can help the model extract implicit information more effectively.

Fourth, the model capability can be improved. The current system uses a small local model (Gemma 2B/7B), which has limited reasoning ability. Using a slightly larger or more capable model would improve answer quality, especially for complex or indirect questions.

Finally, adding an evaluation and feedback loop would help continuously improve the system by identifying failure cases and refining retrieval or prompts accordingly.

Stretch 1 — Chunk Size Experiment

In [47]:
def chunk_text_small(text, size=300):
    words = text.split()
    return [" ".join(words[i:i+size]) for i in range(0, len(words), size)]

In [48]:
def chunk_text_large(text, size=800):
    words = text.split()
    return [" ".join(words[i:i+size]) for i in range(0, len(words), size)]

In [50]:
chunks_small = chunk_text_small(clean_text)
chunks_large = chunk_text_large(clean_text)

bm25_small = BM25Okapi([c.split() for c in chunks_small])
bm25_large = BM25Okapi([c.split() for c in chunks_large])

In [51]:
query = "What is parmanus?"

print("\n--- SMALL CHUNKS ---\n")
print(bm25_small.get_top_n(query.split(), chunks_small, n=1)[0])

print("\n--- LARGE CHUNKS ---\n")
print(bm25_large.get_top_n(query.split(), chunks_large, n=1)[0])

--- SMALL CHUNKS ---

Everything that you see or observe, or feel around is matter. You have learnt that matter consists of tiny particles called atoms. Take a closer look at the picture given above. What do you observe? Do you notice that both living beings, like us, and non-living things, like a house, are ultimately composed of atoms? These atoms are so tiny that they cannot be seen with the naked eye. You may be wondering — Is an atom truly the smallest unit of matter, or can it be divided even further? Scientists, too, have been exploring whether atoms are divisible. If so, what are their constituents and how are these arranged? Let us examine how the concept of atoms emerged and how it has been evolved since then. 8.1 Rediscovering the Roots of Atomic Theory Let us embark on a journey that takes us back more than 2,000 years, to the intellectual landscapes of ancient India and ancient Greece. In these distant yet remarkably parallel civilisations, profound thinkers, such as Acharya Kanada in India, and Leucippus and Democritus in Greece, pondered over the same fundamental question that has continued to inspire human inquiry across centuries — What is everything made up of? Acharya Kanada suggested that if matter (dravya) is divided repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not

--- LARGE CHUNKS ---

Everything that you see or observe, or feel around is matter. You have learnt that matter consists of tiny particles called atoms. Take a closer look at the picture given above. What do you observe? Do you notice that both living beings, like us, and non-living things, like a house, are ultimately composed of atoms? These atoms are so tiny that they cannot be seen with the naked eye. You may be wondering — Is an atom truly the smallest unit of matter, or can it be divided even further? Scientists, too, have been exploring whether atoms are divisible. If so, what are their constituents and how are these arranged? Let us examine how the concept of atoms emerged and how it has been evolved since then. 8.1 Rediscovering the Roots of Atomic Theory Let us embark on a journey that takes us back more than 2,000 years, to the intellectual landscapes of ancient India and ancient Greece. In these distant yet remarkably parallel civilisations, profound thinkers, such as Acharya Kanada in India, and Leucippus and Democritus in Greece, pondered over the same fundamental question that has continued to inspire human inquiry across centuries — What is everything made up of? Acharya Kanada suggested that if matter (dravya) is divided repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all matter is composed of indivisible particles called atoms. That is, the atoms are the fundamental building blocks of matter that cannot be broken down into smaller parts. Dalton’s atomic theory was the first scientific description of how matter is made. It became the starting point for the current understanding of atomic structure. You may be wondering how Dalton’s idea evolved into a model for the structure of the atom. Following Dalton’s theory, scientists were curious to know the answers of the questions: y What are atoms made up of ? y What would atoms look like if we could see them? y What makes the atoms of one element different from the atoms of 8.2 A Short Historical Journey Through Atomic Models More than a hundred years ago, scientists tried to imagine what atoms might look like by proposing simple models. As new experiments were performed and new evidence came to light, these models were changed and improved. Although we now know that the early models were not fully correct, they are still important because they show how science moves forward — one step at a time, driven by curiosity, questioning, and experimentation. Until the late 19th century, atoms were thought to be the smallest, indivisible units of matter. However, scientists discovered that certain elements emit invisible energy and particles called radiation, Fig. 8.1: A line diagram of cathode ray tube High voltage power It was found that the nature of cathode rays was independent of the material of the cathode and the gas filled in the cathode ray tube. It showed that electrons are a fundamental component of all atoms, present in every element. The charge of an electron (–1.602 × 10–19 C) is taken as –1 as a matter of convention and convenience. 8.2.1 Thomson’s model of an atom When J. J. Thomson discovered tiny negatively charged particles called electrons, he faced a puzzle — atoms are neutral, so where is the positive charge present? To solve this, Thomson proposed the atom to be a sphere of positive charge with electrons distributed throughout it (Fig. 8.2). This model was compared to a pudding with plums embedded in it, called the plum pudding model. A more familiar picture would be that of a watermelon (Fig. 8.3), where the red pulp represents the positively charged matter, and the seeds represent electrons distributed throughout the atom. This simple picture, though later replaced, was the first genuine attempt to describe how the atom’s positive and negative charges stay balanced. Fig. 8.3: Watermelon a phenomenon known as radioactivity.

I compared small and large chunk sizes for the query “What is parmanus?”. Both chunking strategies retrieved relevant content, but the smaller chunk was more focused on the Acharya Kanada explanation. The larger chunk contained the same answer plus additional unrelated material from later sections, which can increase noise for the generator. This suggests that smaller chunks are better for precise retrieval in this system


Small chunks: better precision
Large chunks: more context, but more noise
Decision: prefer smaller chunks for final system

Stretch 2— Prompt Comparison
Old prompt vs improved prompt

In [53]:
def answer_with_prompt(question, improved=False):
    tokenized_query = tokenize(question)
    retrieved = bm25.get_top_n(tokenized_query, chunks, n=1)
    context = "\n\n".join(retrieved)

    if improved:
        prompt = f"""
You are a Grade 8 Science assistant.

Use only the context below to answer the question.
If the answer is clearly present, explain it simply.
If the answer is not present, say:
"I cannot answer from the provided chapter."

Context:
{context}

Question:
{question}

Answer in 3-5 simple sentences.
"""
    else:
        prompt = f"""
Context:
{context}

Question:
{question}
Answer:
"""

    response = ollama.chat(
        model="gemma:7b",
        messages=[{"role": "user", "content": prompt}]
    )

    return response["message"]["content"]

In [54]:
print("OLD PROMPT:\n", answer_with_prompt("What is parmanus?", improved=False))
print("\nNEW PROMPT:\n", answer_with_prompt("What is parmanus?", improved=True))

OLD PROMPT:
 Parmanus are the smallest particles that cannot be divided, according to the Sanskrit text Vaisesika Sutras. They are infinitely small and cannot be perceived by the senses.

NEW PROMPT:
 Parmanus are the smallest particles that can no longer be divided, as described in the Sanskrit text Vaisesika Sutras. They are infinitely small and cannot be perceived by the senses.

I compared a minimal prompt with a more explicit grounding prompt on the question “What is parmanus?”. Both prompts produced correct answers, but the improved prompt gave a clearer and more controlled response. This suggests that prompt design affects answer quality even when retrieval is already correct.

Advanced 1 — Guardrail

In [55]:
def is_in_scope(question):
    allowed_keywords = [
        "atom", "atoms", "atomic", "parmanu", "parmanus",
        "electron", "electrons", "proton", "protons",
        "neutron", "neutrons", "nucleus", "dalton",
        "kanada", "atomos", "thomson", "rutherford", "bohr"
    ]
    q = question.lower()
    return any(k in q for k in allowed_keywords)

In [57]:
import ollama

def answer(question):
    if not is_in_scope(question):
        return "This question is outside the scope of the chapter.", []

    tokenized_query = tokenize(question)
    retrieved = bm25.get_top_n(tokenized_query, chunks, n=1)

    context = "\n\n".join(retrieved)

    prompt = f"""
You are a Grade 8 Science assistant.

Use only the context below to answer the question.
If the answer is clearly present, explain it simply.
If the answer is not present, say:
"I cannot answer from the provided chapter."

Context:
{context}

Question:
{question}

Answer in 3-5 simple sentences.
"""

    response = ollama.chat(
        model="gemma:7b",
        messages=[{"role": "user", "content": prompt}]
    )

    return response["message"]["content"], retrieved

In [58]:
print(answer("Who is the Prime Minister of India?")[0])
print(answer("What is parmanus?")[0])

This question is outside the scope of the chapter.
Parmanus are the smallest particles that cannot be divided, described by ancient Indian philosophers as infinitely small and undetectable by the senses.

I implemented a simple keyword-based guardrail to detect whether a question is inside the chapter scope before running retrieval and generation. This reduced unnecessary processing for unrelated queries and made refusal behavior more explicit. For example, the system rejected “Who is the Prime Minister of India?” as out-of-scope, while still answering in-scope textbook questions like “What is parmanus?"

Advanced 2 - Failure Modes

# Failure Modes

## 1. Retrieval mismatch
BM25 sometimes retrieves a chunk that is related to the chapter topic but does not directly answer the question. This caused failures on questions like “What did Dalton propose?” where the answer existed in the chapter but the retrieved chunk was not the most relevant one.

## 2. Chunk noise
Larger chunks introduced extra unrelated information from nearby sections. This made the generator less reliable because the context became noisier. In the chunk-size experiment, smaller chunks produced more focused retrieval.

## 3. Implicit-answer failure
The local model sometimes refused to answer even when the answer was partially present in the context. This happened when the text mentioned a concept indirectly instead of defining it explicitly.

## 4. Corpus contamination
Some activity-style content and extension sections remained in the cleaned corpus. These noisy sections occasionally appeared in retrieval results and reduced answer quality.

## 5. Small-model limitations
The local Gemma model performed reasonably well on direct textbook questions but struggled with ambiguous wording and deeper reasoning compared to stronger hosted models.

# Project Summmary

This project builds a retrieval-based study assistant for a Grade 8 science chapter using BM25 and a local LLM. The system retrieves relevant text chunks and generates grounded answers while avoiding hallucinations. It was evaluated on multiple question types and enhanced through chunk-size experiments, prompt improvements, and a guardrail for out-of-scope queries. The results show that retrieval quality and prompt design are critical for system performance.

BONUS 1

In [40]:
ans, retrieved = answer("What is parmanus?")

print("\n=== ANSWER ===\n")
print(ans)

print("\n=== SUPPORTING CHUNK ===\n")
print(retrieved[0])

=== RETRIEVED CONTEXT ===
repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all matter is composed of indivisible particles called atoms. That is, the atoms are the fundamental building blocks of matter that cannot be broken down into smaller parts. Dalton’s atomic theory was the first scientific description of how matter is made. It became the starting point for the current understanding of atomic structure. You may be wondering how Dalton’s idea evolved into a model for the structure of the atom. Following Dalton’s theory, scientists were curious to know the answers of the questions: y What are
=========================

=== ANSWER ===

Parmanus are the smallest particles that cannot be divided, described as infinitely small and undetectable by the senses. They are the fundamental building blocks of matter, forming combinations such as dyads and triads to create the entire material universe.

=== SUPPORTING CHUNK ===

repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all matter is composed of indivisible particles called atoms. That is, the atoms are the fundamental building blocks of matter that cannot be broken down into smaller parts. Dalton’s atomic theory was the first scientific description of how matter is made. It became the starting point for the current understanding of atomic structure. You may be wondering how Dalton’s idea evolved into a model for the structure of the atom. Following Dalton’s theory, scientists were curious to know the answers of the questions: y What are

The system shows the retrieved chunk along with the generated answer, which improves transparency and makes it easier to verify whether the answer is grounded in the source text. In the “What is parmanus?” example, the retrieved chunk explicitly states that parmanus are the smallest particles that cannot be divided and are infinitely small. The generated answer correctly summarizes that information without adding unsupported claims.

BONUS 2

In [41]:
def compare_chunks(question):
    tokenized_query = tokenize(question)

    r1 = bm25.get_top_n(tokenized_query, chunks, n=1)
    r3 = bm25.get_top_n(tokenized_query, chunks, n=3)

    print("\n--- n=1 ---\n")
    print(r1[0])

    print("\n--- n=3 ---\n")
    for i, c in enumerate(r3):
        print(f"\nChunk {i+1}:\n{c}")

In [42]:
compare_chunks("What is parmanus?")

--- n=1 ---

repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all matter is composed of indivisible particles called atoms. That is, the atoms are the fundamental building blocks of matter that cannot be broken down into smaller parts. Dalton’s atomic theory was the first scientific description of how matter is made. It became the starting point for the current understanding of atomic structure. You may be wondering how Dalton’s idea evolved into a model for the structure of the atom. Following Dalton’s theory, scientists were curious to know the answers of the questions: y What are

--- n=3 ---


Chunk 1:
repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and cannot be perceived by the senses. Combinations of these forms dyads (groups of two parmanus) and triads (groups of three parmanus), and so on. It is out of these combinations that the whole of the material universe including the bodies of living beings is created. However, this description does not specify the proportions in which parmanus combine to form different substances. The Greek philosophers Leucippus and Democritus also proposed a similar idea. They called these indivisible particles atomos (in Greek, atomos means indivisible). You must remember that the concept of ‘atom’ originated as an imaginary idea rather than from experimental observations. Many centuries later, in 1808, John Dalton proposed his atomic theory. It was based on scientific experiments of that time. He proposed that all matter is composed of indivisible particles called atoms. That is, the atoms are the fundamental building blocks of matter that cannot be broken down into smaller parts. Dalton’s atomic theory was the first scientific description of how matter is made. It became the starting point for the current understanding of atomic structure. You may be wondering how Dalton’s idea evolved into a model for the structure of the atom. Following Dalton’s theory, scientists were curious to know the answers of the questions: y What are

Chunk 2:
Everything that you see or observe, or feel around is matter. You have learnt that matter consists of tiny particles called atoms. Take a closer look at the picture given above. What do you observe? Do you notice that both living beings, like us, and non-living things, like a house, are ultimately composed of atoms? These atoms are so tiny that they cannot be seen with the naked eye. You may be wondering — Is an atom truly the smallest unit of matter, or can it be divided even further? Scientists, too, have been exploring whether atoms are divisible. If so, what are their constituents and how are these arranged? Let us examine how the concept of atoms emerged and how it has been evolved since then. 8.1 Rediscovering the Roots of Atomic Theory Let us embark on a journey that takes us back more than 2,000 years, to the intellectual landscapes of ancient India and ancient Greece. In these distant yet remarkably parallel civilisations, profound thinkers, such as Acharya Kanada in India, and Leucippus and Democritus in Greece, pondered over the same fundamental question that has continued to inspire human inquiry across centuries — What is everything made up of? Acharya Kanada suggested that if matter (dravya) is divided repeatedly, you will reach a stage where you would encounter the smallest particles that can no longer be divided. He called these particles parmanus. His ideas are recorded in the Sanskrit text Vaisesika Sutras. A parmanu is infinitely small and

Chunk 3:
any three elements. y To learn more about atoms, you can explore the links given below: The Quest Continues ... Is it possible to completely understand everything that happens inside an The Journey Beyond

I compared retrieval with top-k = 1 and top-k = 3 for the question “What is parmanus?”. With n=1, the retrieved context was focused and directly contained the answer, which helped the model generate a correct grounded response. With n=3, additional chunks introduced noise, including an irrelevant activity-style chunk. This showed that for a small local model, tighter retrieval produced better grounded answers than broader retrieval.

I chose n=1 for the final system because it reduced noisy context and improved answer quality on direct textbook questions.

BONUS 3

In [43]:
ans, retrieved = answer("Who is the Prime Minister of India?")
print(ans)

=== RETRIEVED CONTEXT ===
may wonder that since all the protons with like charges are squished together in a nucleus why do they not push each Think of it this way — every proton inside the nucleus repels every other proton because they all carry positive charge. Neutrons being neutral help reduce this repulsion by intervening and increasing the distance between protons, and also by strengthening the force, called the nuclear force, that binds all particles together. So, heavier atoms need many more neutrons to hold everything in the nucleus tightly bound. Threads of Curiosity Meet a Scientist Laboratory at the University of Cambridge, solved a key puzzle in 1932, when he discovered the neutron. This breakthrough explained atomic mass and earned him the Nobel Prize in Physics in 1935. The neutron immediately enabling scientists to probe nuclear secrets, and sparked a chain of discoveries in understanding and harnessing atomic energy. Ready to Go Beyond The discovery of the neutron opened a new era in atomic physics. uncharged, can easily penetrate nuclei, leading such as the creation of elements and the splitting of uranium atoms. This gave birth to the ʻatomic ageʼ, allowing the development of both nuclear power and What if ... an atom had no empty space? How would this have affected the size of various objects? Centre (BARC, Fig. 8.8), Mumbai, leads advanced neutron-scattering experiments using reactors, such electrodes, and drug molecules, helping develop better medicines, alloys right here in India. Research and explore more about Dhruva! India's Scientific Contributions Fig.
=========================
The provided text does not contain any information regarding the Prime Minister of India, so I am unable to answer this question from the given context.

I tested the system with an out-of-scope question: “Who is the Prime Minister of India?” Although the retriever returned an unrelated science chunk, the model did not hallucinate an answer. Instead, it correctly refused and stated that the answer was not present in the given context. This shows that the grounding prompt worked and helped prevent unsupported answers.

In [44]:
question = "Who is the Prime Minister of India?"
correct = "N/A"
grounded = "yes"
refusal_appropriate = "yes"

In [45]:
new_row = {
    "question": "Who is the Prime Minister of India?",
    "answer": "The provided text does not contain any information regarding the Prime Minister of India, so I am unable to answer this question from the given context.",
    "retrieved_chunk": retrieved[0] if retrieved else "",
    "correct": "N/A",
    "grounded": "yes",
    "refusal_appropriate": "yes"
}

df.loc[len(df)] = new_row
df

,question,answer,retrieved_chunk,correct,grounded,refusal_appropriate
0,What is parmanus?,Parmanus are the smallest particles that canno...,"repeatedly, you will reach a stage where you w...",yes,yes,N/A
1,Who was Acharya Kanada?,The provided text does not contain any informa...,"Everything that you see or observe, or feel ar...",no,yes,no
2,What did Dalton propose about atoms?,The provided text does not contain any informa...,each statement. (i) Electrons lose energy whil...,no,yes,yes
3,What does atomos mean?,The provided text does not contain any informa...,in two isotopic forms. One isotope has a mass ...,no,yes,yes
4,What is an atom?,"An atom is the basic building block of matter,...",of atomic energy in India. He established key ...,yes,yes,N/A
5,Who is the Prime Minister of India?,The provided text does not contain any informa...,may wonder that since all the protons with lik...,N/A,yes,yes

In [46]:
df.to_csv("evaluation_results.csv", index=False)

The bonus experiments showed that retrieval quality strongly affects answer quality. Focused retrieval (n=1) worked better than broader retrieval (n=3) for the local model, and the refusal behavior on out-of-scope questions demonstrated that the system remained grounded instead of hallucinating.

# Final Project Write-Up: Retrieval-Ready Study Assistant

1. Overview

This project implements a Retrieval-Augmented Generation (RAG) system to answer Grade 8 science questions from a textbook chapter on atomic structure. The system retrieves relevant content from the chapter and generates grounded answers using a local language model (Gemma via Ollama).

The main objective is to ensure that answers are factually correct, grounded in the source text, and free from hallucination.

2. System Design

The system consists of the following pipeline:

Step 1: Text Processing
Extracted text from the textbook
Removed noise such as headings, activities, and irrelevant sections
Cleaned and normalized the text
Step 2: Chunking
Divided the text into chunks
Used chunking to enable efficient retrieval
Later experimented with different chunk sizes (small vs large)
Step 3: Retrieval (BM25)
Used BM25 for keyword-based retrieval
Retrieved top relevant chunks for each query
Final system uses top-1 retrieval (n=1) for better precision
Step 4: Answer Generation
Used a local LLM (Gemma via Ollama)
Prompt enforces:
Use only provided context
No external knowledge
Refuse if answer not present

3. Evaluation

The system was tested using multiple types of questions:

Direct textbook questions
Conceptual questions
Out-of-scope questions

Evaluation metrics:

Correctness
Groundedness
Refusal appropriateness
Key Observations
Works well on direct questions
Produces grounded answers
Correctly refuses unrelated questions

4. Failure Analysis

Failure 1: Acharya Kanada question
Model refused even though partial info existed
Cause: no explicit definition in chunk
Failure 2: Dalton question
Incorrect chunk retrieved
Cause: BM25 retrieval limitation
Failure 3: Atomos question
Answer exists but not retrieved
Cause: chunk separation

5. Stretch Experiments

5.1 Chunk Size Experiment
Compared small vs large chunks
Small chunks gave better precision
Large chunks introduced noise
5.2 Prompt Comparison
Compared basic vs structured prompt
Improved prompt gave more controlled and clearer answers

6. Advanced Improvements

6.1 Guardrail
Added keyword-based scope detection
Prevents answering unrelated questions
Improves system safety
6.2 Failure Modes Documentation
Created failure_modes.md
Identified key issues:
retrieval mismatch
chunk noise
implicit-answer failure
small-model limitations

7. Bonus Experiments

Displayed retrieved chunks (explainability)
Compared n=1 vs n=3 retrieval
Tested out-of-scope refusal behavior

8. Key Insights

Retrieval quality matters more than model size
Smaller, focused context improves answers
Prompt design influences model behavior
Guardrails help prevent misuse and hallucination

9. Conclusion

This project demonstrates a complete RAG pipeline with retrieval, generation, evaluation, and improvement cycles. It highlights that engineering choices such as chunking, retrieval, and prompting have a larger impact on performance than simply using a bigger model.